version: '3'

services:
  web:
    build: .
    environment:
      JDBC_URL: jdbc:mysql://root:password@mysql/sakila?useSSL=false
      ES_HOSTS: elasticsearch
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
    ports:
      - 8080:8080
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./src/test/resources/sql/sakila-schema.sql:/docker-entrypoint-initdb.d/01-sakila-schema.sql
      - ./src/test/resources/sql/sakila-data.sql:/docker-entrypoint-initdb.d/02-sakila-data.sql
      - ./src/test/resources/sql/custom.sql:/docker-entrypoint-initdb.d/03-custom.sql
    # Use tmpfs for /var/lib/mysql
    # https://stackoverflow.com/questions/42226418/how-to-move-postresql-to-ram-disk-in-docker
    tmpfs:
      - /var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
