version: '3'

services:
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data/sakila-schema.sql:/docker-entrypoint-initdb.d/01-sakila-schema.sql
      - ./data/sakila-data.sql:/docker-entrypoint-initdb.d/02-sakila-data.sql