USE sakila;

CREATE TABLE mail (
  mail_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(100) NOT NULL,
  `to` VARCHAR(100) NOT NULL,
  cc VARCHAR(100) NOT NULL DEFAULT '',
  subject VARCHAR(255) NOT NULL,
  body TEXT DEFAULT NULL,
  is_succeeded TINYINT NULL,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY  (mail_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;